version: '3.8'

services:
  postgres:
    container_name: user-db
    image: postgres:17
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    restart: always
    image: redis:7.2
    ports:
      - "6379:6379"
