version: '3.8'

services:
  postgres:
    container_name: user-db
    image: postgres:17
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: user-api
    depends_on:
     postgres:
       condition: service_healthy
     redis:
       condition: service_healthy
    environment:
     SPRING_PROFILES_ACTIVE: docker
    ports:
     - "8080:8080"

volumes:
  pgdata:
